export enum EmailTemplate {
  WAITLIST = "WAITLIST",
  LOGIN_NOTIFICATION = "LOGIN_NOTIFICATION",
  FEEDBACK = "FEEDBACK",
  DELETION_REQUEST_ADMIN = "DELETION_REQUEST_ADMIN",
  DELETION_REQUEST_USER = "DELETION_REQUEST_USER",
}
