export const inspirationalQuotes = [
  "The blank page is not a void, but a canvas waiting for your thoughts.",
  "Write with purpose, edit with precision, publish with confidence.",
  "In the quiet space between words, creativity finds its voice.",
  "Clear writing begins with clear thinking.",
  "First drafts don't need to be perfect, they just need to exist.",
  "The best tool for writing is the one you forget you're using.",
  "Words are the bridge between imagination and reality.",
  "Sometimes the most profound ideas come from the simplest sentences.",
  "A distraction-free environment is the soil in which ideas grow.",
  "Writing isn't about finding time, it's about making time.",
  "When you remove the noise, you can hear your own thoughts.",
  "The journey of a thousand pages begins with a single word.",
  "Clarity comes not from complexity, but from purposeful simplicity.",
  "Let your first draft be raw, your final draft be refined.",
  "The greatest enemy of creativity is interruption.",
  "Ideas don't wait for perfect conditions. Write now.",
  "Minimalism in writing isn't about less, but about exactly enough.",
  "What you leave out is just as important as what you put in.",
  "Words have energy. Choose them wisely.",
  "The rhythm of your writing reflects the rhythm of your thinking.",
  "Technology should amplify creativity, not distract from it.",
  "Write to discover what you know.",
  "The best writing feels like a conversation with a thoughtful friend.",
  "In the space between keystrokes, inspiration waits.",
  "Creativity thrives in the absence of judgment.",
  "Behind every blank page is an universe of possibility.",
  "Good writing is clear thinking made visible.",
  "The most powerful tool in writing is often the delete key.",
  "Flow happens when you forget you're writing.",
  "True productivity isn't measured in word count, but in clarity of thought.",
  "AI doesn't replace your voice—it amplifies it.",
  "The greatest ideas often come when you're not trying to force them.",
  "Write like no one is reading, edit like everyone is.",
  "A quiet mind produces the loudest ideas.",
  "Consistency builds skill; inspiration builds art.",
  "The perfect environment for writing is one you don't notice.",
  "Your voice becomes clearer with every word you write.",
  "Minimalism isn't about emptiness—it's about intentionality.",
  "Let your tools fade into the background so your ideas can come to the foreground.",
  "Writing is thinking in slow motion.",
  "The best ideas need room to breathe.",
  "Focus is not the absence of distraction, but the presence of intention.",
  "Simple tools lead to profound thoughts.",
  "Your first sentence opens a door. Your last one should close it gently.",
  "Clarity is kindness to your future readers—and to yourself.",
  "Write to express, not to impress.",
  "The gap between what you envision and what you create closes with practice.",
  "Ideas flow naturally when you remove artificial barriers.",
  "The cursor blinks with possibility.",
  "The best writing happens when the technology disappears.",
  "Don't wait for inspiration. Create the conditions for it to find you.",
  "Every sentence should earn its place on the page.",
  "Great writing doesn't shout; it resonates.",
  "Your words today are seeds for tomorrow's garden of thought.",
  "Blank spaces in design create room for thought.",
  "Write with the courage to be misunderstood.",
  "The path to clarity is paved with deleted drafts.",
  "A minimalist approach to writing brings maximum impact.",
  "AI is a collaborator, not a replacement for your unique voice.",
  "The right words in the right order can change everything.",
  "Inspiration is fleeting; capture it in a distraction-free space.",
  "Words are the architects of understanding.",
  "In simplicity, there is profound power.",
  "Writing isn't just recording thoughts—it's discovering them.",
  "Creativity thrives within constraints.",
  "Let your ideas flow now; let your inner critic edit later.",
  "The finest writing feels inevitable, as if it couldn't be any other way.",
  "Focus is the hidden ingredient in all great writing.",
  "The difference between the right word and the almost right word is everything.",
  "Your writing environment shapes your writing experience.",
  "Clarity doesn't happen by accident; it's a deliberate choice.",
  "The best technology feels like an extension of yourself.",
  "Write from your core, edit from your craft.",
  "Today's stream of consciousness is tomorrow's refined idea.",
  "In the silence between distractions, your true voice emerges.",
  "A good writing space is invisible—all you see are your ideas.",
  "Your words matter. Choose a space where they can matter most.",
  "The magic isn't in the tools, but in how they free your mind to create.",
  "Simplicity is the ultimate sophistication in both design and writing.",
  "Ideas don't arrive on schedule—be ready when they appear.",
  "Create the silence your thoughts need to become words.",
  "The delete key is often the most powerful tool for clarity.",
  "Write first, judge later.",
  "Small daily writing compounds into remarkable results.",
  "When your tool becomes invisible, your creativity becomes visible.",
  "The distance between idea and expression is shortened with practice.",
  "Great writing emerges from the courage to start and the discipline to finish.",
  "Clarity of space leads to clarity of thought.",
  "Write until the words surprise you.",
  "The best AI knows when to help and when to step back.",
  "A clean page creates room for messy first drafts.",
  "The most beautiful writing often starts as the most chaotic thinking.",
  "Simplicity is not the goal. Clarity is.",
  "Write with intention, edit with attention.",
  "The perfect writing environment doesn't interrupt your flow of thought.",
  "In the white space between paragraphs, understanding grows.",
  "Writing is the art of thinking in public.",
  "The words you're looking for are already within you—they just need space.",
];
